### ISSUE TITLE
[Add function] 키워드,카테고리별 검색

### ISSUE THREAD

**Issue by suyeon-9706** [2018bottomUpProject/User-participating-service-apps#13]
google map, places를 연동하여 현재 gps 주변 위치를 중심으로 카테고리별 검색을 가능하도록 한다.

**Comment by sy06** [comment]
현재 디바이스 gps 정보를 기반으로 카테고리 검색을 하여 주변 장소를 지도에 나타나도록 구현함(google places api연동)
메뉴를 실행할 때, 사용자가 필요한 권한을 킨 후 해당 메뉴를 사용할 수 있도록 함.
